### ISSUE TITLE
[CLOSED] unit tests fail

### ISSUE THREAD

**Issue by ruffinevans** [ruffinevans/sivtempfit#4]
<a href="https://github.com/vnmanoharan"><img src="https://avatars.githubusercontent.com/u/6162404?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vnmanoharan](https://github.com/vnmanoharan)**
_Wednesday Apr 13, 2016 at 15:03 GMT_
_Originally opened as https://github.com/p201-sp2016/sivtempfit/issues/4_

----

Error message is below:
```
C:\Users\vnm\Documents\code\p201-sp2016\SiVTempFit-RE [master]> nosetests
C:\Users\vnm\Anaconda3\lib\site-packages\matplotlib\__init__.py:872: UserWarning: axes.color_cycle is deprecated and rep
laced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))
E
======================================================================
ERROR: Failure: ImportError (No module named 'example_data_test')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\vnm\Anaconda3\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Users\vnm\Anaconda3\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Users\vnm\Anaconda3\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Users\vnm\Anaconda3\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Users\vnm\Anaconda3\lib\imp.py", line 244, in load_module
    return load_package(name, filename)
  File "C:\Users\vnm\Anaconda3\lib\imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\vnm\Documents\code\p201-sp2016\SiVTempFit-RE\SiVTempFit\tests\__init__.py", line 7, in <module>
    import example_data_test
ImportError: No module named 'example_data_test'

----------------------------------------------------------------------
Ran 1 test in 3.701s

FAILED (errors=1)
```

**Comment by ruffinevans** [comment]
<a href="https://github.com/vnmanoharan"><img src="https://avatars.githubusercontent.com/u/6162404?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vnmanoharan](https://github.com/vnmanoharan)**
_Wednesday Apr 13, 2016 at 15:04 GMT_

----

I'm not sure it would run anyway, even if it could find the file, since the file uses `basestring`, which is deprecated in Python 3. 

As a general rule, make sure the tests run before updating the master branch. If you are going to make big changes that will necessitate breaking the tests, you can do those in another branch, then update the tests before merging with master.

**Comment by ruffinevans** [comment]
<a href="https://github.com/catherinezucker"><img src="https://avatars.githubusercontent.com/u/18339657?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [catherinezucker](https://github.com/catherinezucker)**
_Thursday Apr 14, 2016 at 00:58 GMT_

----

Hi Ruffin: I had the same problem. Just replace "basestring" with "str" and it should work (if it can find the file)

**Comment by ruffinevans** [comment]
<a href="https://github.com/ruffinevans"><img src="https://avatars.githubusercontent.com/u/7091851?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ruffinevans](https://github.com/ruffinevans)**
_Thursday Apr 14, 2016 at 15:40 GMT_

----

Unit test framework now works. The tests themselves aren't meaningful, but this is a separate issue. Thanks!
